import React, { useState } from 'react';
import { FiChevronDown, FiChevronUp } from 'react-icons/fi';

interface FAQItemProps {
  question: string;
  answer: React.ReactNode;
}

const FAQItem: React.FC<FAQItemProps> = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-gray-200 py-5">
      <button
        className="flex w-full justify-between items-center text-left focus:outline-none"
        onClick={() => setIsOpen(!isOpen)}
        aria-expanded={isOpen}
      >
        <h3 className="text-lg font-semibold">{question}</h3>
        <span className="text-primary ml-4">
          {isOpen ? <FiChevronUp className="w-5 h-5" /> : <FiChevronDown className="w-5 h-5" />}
        </span>
      </button>
      {isOpen && (
        <div className="mt-3 text-gray-600">
          {answer}
        </div>
      )}
    </div>
  );
};

const PartnerFAQ: React.FC = () => {
  const faqs: FAQItemProps[] = [
    {
      question: "What types of partnership programs does Deriv offer?",
      answer: (
        <p>
          Deriv offers several partnership types including affiliate programs for passive income, 
          IB programs for building brokerage businesses, content creator programs for monetizing audiences, 
          API partnerships for custom solutions, and referral programs. Each program is designed to suit 
          different business models and objectives.
        </p>
      )
    },
    {
      question: "How do commission tiers work?",
      answer: (
        <>
          <p className="mb-2">
            Our commission structure is tier-based, with increasing rates as you progress:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Starter tier: Base commission rates</li>
            <li>Silver tier: 1.1x multiplier on base rates</li>
            <li>Gold tier: 1.15x multiplier on base rates</li>
            <li>Diamond tier: 1.2x multiplier on base rates</li>
          </ul>
          <p className="mt-2">
            Your tier is determined by your clients' trading volume and client acquisition rate.
          </p>
        </>
      )
    },
    {
      question: "What is the Master Partner Program?",
      answer: (
        <p>
          The Master Partner Program allows you to build your own network of sub-partners. 
          You'll earn 20% of the commissions generated by partners you bring into the Deriv ecosystem. 
          This program is available to all partners across all tiers, making it an excellent opportunity 
          to scale your partnership business.
        </p>
      )
    },
    {
      question: "How does the 121 Partner Program work?",
      answer: (
        <>
          <p className="mb-2">
            The 121 Partner Program is our premium service designed for high-performing partners who need strategic guidance to scale their business. Benefits include:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Dedicated business development manager</li>
            <li>Strategic consulting and growth planning</li>
            <li>Priority technical support</li>
            <li>Custom marketing resources and co-sponsorship opportunities</li>
            <li>Early access to new Deriv products and features</li>
          </ul>
          <p className="mt-2">
            Qualification is based on client acquisition rate, trading volume, and long-term growth potential.
          </p>
        </>
      )
    },
    {
      question: "What marketing support do you provide partners?",
      answer: (
        <p>
          We provide comprehensive marketing support including branded marketing materials, 
          conversion-optimized landing pages, content creation assistance, educational webinars, 
          and for premium partners, co-sponsorship opportunities for events. All partners receive 
          access to our Partner Portal with real-time performance analytics and marketing resources.
        </p>
      )
    },
    {
      question: "How often are commissions paid out?",
      answer: (
        <p>
          Commissions are calculated daily and paid out monthly. Payments are typically processed 
          by the 15th of each month for the previous month's earnings. We offer multiple payment 
          methods including bank transfers, e-wallets, and cryptocurrencies to accommodate partners worldwide.
        </p>
      )
    },
    {
      question: "Do I need trading experience to become a partner?",
      answer: (
        <p>
          No, trading experience is not required to become a Deriv partner. Many successful partners 
          have no prior trading background. What's important is your ability to connect with potential 
          clients through your audience, network, or marketing expertise. We provide comprehensive 
          product training and marketing materials to help you succeed.
        </p>
      )
    },
  ];

  return (
    <section className="py-16 bg-white">
      <div className="container-custom">
        <div className="text-center mb-12">
          <span className="text-primary font-semibold tracking-wider uppercase text-sm">FAQs</span>
          <h2 className="text-3xl md:text-4xl font-bold mt-2 mb-4">Common Partner Questions</h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Find answers to frequently asked questions about our partnership programs
          </p>
        </div>

        <div className="max-w-3xl mx-auto">
          {faqs.map((faq, index) => (
            <FAQItem key={index} question={faq.question} answer={faq.answer} />
          ))}
        </div>

        <div className="text-center mt-12">
          <p className="text-gray-600 mb-4">Still have questions?</p>
          <a
            href="mailto:partners@deriv.com"
            className="btn bg-transparent border-2 border-primary text-primary hover:bg-primary hover:text-white transition-colors"
          >
            Contact Partner Support
          </a>
        </div>
      </div>
    </section>
  );
};

export default PartnerFAQ; 